### ISSUE TITLE
Android support / Termux support

### ISSUE THREAD

**Issue by alexanderadam** [svartalf/rust-battery#69] opened 2020-08-07 21:29 UTC
I tried to compile [starship](https://github.com/starship/starship) on a Samsung Galaxy Tab s6 in [Termux](https://github.com/termux) and it failed with the message `Support for this target OS is not implemented yet!`

![Compile error of rust-battery in Termux](https://user-images.githubusercontent.com/372620/89689997-d3d16200-d905-11ea-9f59-089fe65f5ae3.jpg)

```
error: Support for this target OS is not implemented yet!
 You may want to create an issue: https://github.com/svartalf/rust-battery/issues/new
  --> /data/data/com.termux/files/home/.cargo/registry/src/github.com-1ecc6299db9ec823/battery-0.7.5/src/platform/mod.rs:27:9
   |
27 | /         compile_error!("Support for this target OS is not implemented yet!\n \
28 | |             You may want to create an issue: https://github.com/svartalf/rust-battery/issues/new");
   | |___________________________________________________________________________________________________^

error[E0432]: unresolved import `crate::platform::Device`
 --> /data/data/com.termux/files/home/.cargo/registry/src/github.com-1ecc6299db9ec823/battery-0.7.5/src/types/battery.rs:5:5
  |
5 | use crate::platform::Device;
  |     ^^^^^^^^^^^^^^^^^^^^^^^ no `Device` in `platform`

error[E0432]: unresolved import `crate::platform::Iterator`
 --> /data/data/com.termux/files/home/.cargo/registry/src/github.com-1ecc6299db9ec823/battery-0.7.5/src/types/iterator.rs:3:5
  |
3 | use crate::platform::Iterator as PlatformIterator;
  |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ no `Iterator` in `platform`

error[E0432]: unresolved import `crate::platform::Iterator`
 --> /data/data/com.termux/files/home/.cargo/registry/src/github.com-1ecc6299db9ec823/battery-0.7.5/src/types/manager.rs:5:5
  |
5 | use crate::platform::Iterator as PlatformIterator;
  |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ no `Iterator` in `platform`

error[E0432]: unresolved import `crate::platform::Manager`
 --> /data/data/com.termux/files/home/.cargo/registry/src/github.com-1ecc6299db9ec823/battery-0.7.5/src/types/manager.rs:6:5
  |
6 | use crate::platform::Manager as PlatformManager;
  |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ no `Manager` in `platform`

error: aborting due to 5 previous errors

For more information about this error, try `rustc --explain E0432`.
error: could not compile `battery`.

To learn more, run the command again with --verbose.
warning: build failed, waiting for other jobs to finish...
error: failed to compile `starship v0.44.0`, intermediate artifacts can be found at `/data/data/com.termux/files/usr/tmp/cargo-install5qDCt5`

Caused by:
  build failed
```

Please tell me if I can help in any way (except from doing Rust).

**PS:** Maybe an [Android Emulator](https://developer.android.com/studio/run/emulator) or [termux-docker](https://github.com/xeffyr/termux-docker) can help.

**Comment by svartalf** [comment] 2020-08-09 08:22
Duplicate of https://github.com/svartalf/rust-battery/issues/33, see it for more details.

**Closed by svartalf** 2020-08-09 08:22 UTC
